services:
  backend:
    build:
      context: ./compression-backend
      dockerfile: Dockerfile
    container_name: img-backend
    restart: unless-stopped
    volumes:
      # 持久化上传文件
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./compression-frontend
      dockerfile: Dockerfile
    container_name: img-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  uploads_data:
